# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\David\Documents\GitHub\yt-dlp-ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(643, 582)
        self.downloadButton = QtWidgets.QPushButton(Widget)
        self.downloadButton.setGeometry(QtCore.QRect(280, 480, 351, 61))
        self.downloadButton.setObjectName("downloadButton")
        self.formatListView = QtWidgets.QListView(Widget)
        self.formatListView.setGeometry(QtCore.QRect(10, 20, 261, 521))
        self.formatListView.setObjectName("formatListView")
        self.videoQualityCB = QtWidgets.QComboBox(Widget)
        self.videoQualityCB.setGeometry(QtCore.QRect(280, 110, 351, 41))
        self.videoQualityCB.setObjectName("videoQualityCB")
        self.videoQualityCB.addItem("")
        self.videoQualityCB.addItem("")
        self.videoQualityCB.addItem("")
        self.audioOnlyCheck = QtWidgets.QCheckBox(Widget)
        self.audioOnlyCheck.setGeometry(QtCore.QRect(290, 190, 91, 22))
        self.audioOnlyCheck.setObjectName("audioOnlyCheck")
        self.downloadProgress = QtWidgets.QProgressBar(Widget)
        self.downloadProgress.setGeometry(QtCore.QRect(280, 450, 351, 23))
        self.downloadProgress.setProperty("value", 0)
        self.downloadProgress.setTextVisible(True)
        self.downloadProgress.setObjectName("downloadProgress")
        self.videoOnlyCheck = QtWidgets.QCheckBox(Widget)
        self.videoOnlyCheck.setGeometry(QtCore.QRect(290, 160, 81, 22))
        self.videoOnlyCheck.setObjectName("videoOnlyCheck")
        self.checkLinkButton = QtWidgets.QPushButton(Widget)
        self.checkLinkButton.setGeometry(QtCore.QRect(279, 70, 351, 24))
        self.checkLinkButton.setObjectName("checkLinkButton")
        self.setDownload = QtWidgets.QPushButton(Widget)
        self.setDownload.setGeometry(QtCore.QRect(330, 550, 251, 21))
        self.setDownload.setObjectName("setDownload")
        self.enterLink = QtWidgets.QLineEdit(Widget)
        self.enterLink.setGeometry(QtCore.QRect(280, 30, 351, 31))
        self.enterLink.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enterLink.setAutoFillBackground(False)
        self.enterLink.setObjectName("enterLink")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.downloadButton.setText(_translate("Widget", "Start Download"))
        self.videoQualityCB.setItemText(0, _translate("Widget", "1080p"))
        self.videoQualityCB.setItemText(1, _translate("Widget", "720p"))
        self.videoQualityCB.setItemText(2, _translate("Widget", "480p"))
        self.audioOnlyCheck.setText(_translate("Widget", "Audio Only"))
        self.videoOnlyCheck.setText(_translate("Widget", "Video Only"))
        self.checkLinkButton.setText(_translate("Widget", "Check Link"))
        self.setDownload.setText(_translate("Widget", "Set Download Location"))
        self.enterLink.setText(_translate("Widget", "Enter Link"))
